[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

[default_session]
# The default session, also what is used when a user logs in.
command = "tuigreet --cmd niri --remember --remember-session --asterisks --time --time-format '%I:%M %p | %a %d-%m-%y'"
user = "greeter"
