[customizations.installer.kickstart]
contents = """
%post
# !!! PRE-CONFIGURED BOOTC SWITCH !!!
# The Justfile will inject the correct command here.
# If local: It will be a comment (no switch).
# If remote: It will be 'bootc switch ... ghcr.io/...'
@@BOOTC_SWITCH_COMMAND@@
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime"
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Timezone" 
  "org.fedoraproject.Anaconda.Modules.Services",
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Users",        # Declaratively defined
  "org.fedoraproject.Anaconda.Modules.Subscription",
]
