[customizations.installer.kickstart]
contents = """
# Switch to Graphical mode (Interactive GUI)
graphical

lang en_US.UTF-8
keyboard --xlayouts='us'

%post --erroronfail --log=/var/log/anaconda/post-install.log
@@BOOTC_SWITCH_COMMAND@@
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Timezone", 
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Localization", 
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Users",       
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription",
]
